### ISSUE TITLE
A normalization bug on Unity2022.

### ISSUE THREAD

**Issue by Dragon-Perez** [vrm-c/UniVRM#2201] opened 2023-12-14 21:03 UTC
### **Environment**
Unity: 2022.3.6f1
UniVRM: UniVRM-0.116.0_0f6c

### **Describe problem:**

Hi, I'm trying to export my model into the vrm but when I import it, it looks mesh up or broken.

![imagen_2023-12-14_220319788](https://github.com/vrm-c/UniVRM/assets/73560199/bc982505-2303-4988-ab64-38cfb7a30300)

Post-Note: It seems the unity version was the problem? Cuz I went to the other unity and it worked.

**Comment by tonby** [comment] 2023-12-20 06:28
I encountered the same bug where the exported avatar appears incorrectly when "Pose Freeze" is turned on. It seems to be related to normalization. Avatars exported with "Pose Freeze" off display correctly.
Upon closer inspection, it appears that the bone transform of the bugged avatar is not normalized.
https://imgur.com/a/lPy8KNh
The first picture depicts an avatar exported on Unity 2021.3.4f1, while the second avatar was exported on Unity 2022.3.6f1.
If possible, I suggest changing the title of this issue to something like "A normalization bug on Unity2022."

Versions:
Unity: 2022.3.6f1
UniVRM-0.116.0_0f6c

**Comment by MaCoRig** [comment] 2023-12-20 13:54
We have run into the same issue in Unity 2021.3.16f1—ever since updating the VRM package to 0.116.0 the exports with pose freeze have been broken.

As a workaround, we have been able to freeze the mesh using the glTF Mesh Utility, but it would be great if this could be fixed in the VRM export, again!

**Comment by esperecyan** [comment] 2023-12-28 10:33
Unity 2023.2.3f1でも同じ問題が起きます。
UniVRM-0.115.0へダウングレードすると正常にエクスポートできました。

**Comment by FrostyTart** [comment] 2024-01-02 22:05
I have also run into this issue with unity versions 2022.3.16f1 and 2021.3.0f1 with the VRM Package 0.116.0.

**Comment by ousttrue** [comment] 2024-01-04 06:27
Confirmed reproduction with `v0.116`.
This is a regression bug in the normalization function.
I'll fix it right away.

**Comment by ousttrue** [comment] 2024-01-04 07:14
vrm export 時に下記の処理が抜けている。

https://github.com/vrm-c/UniVRM/blob/ffd4e63bcd499ae1a560a401b713699ba64a9ddd/Assets/VRM/Runtime/SkinnedMeshUtility/VrmMeshUtility.cs#L117

animator.avatar を代入するときに代入前の値を維持しようとする挙動があり、
代入前後で avatar の元のヒエラルキーが変化(例えば正規化)していると壊れる。
代入するのではなく、animator を destroy して作り直す。

**Closed** 2024-01-09 04:46 UTC
Labels: bug, exporter, mesh
