### ISSUE TITLE
[0.x][springbone][center] Imported VRM hair and clothes goes to the left no matter the position

### ISSUE THREAD

**Issue by TheR20** [vrm-c/UniVRM#2440] opened 2024-09-22 09:40 UTC
- UniVRM version: `0.126.0`
- Unity version: `Unity-2022.3.17`
- OS: `Windows 10`

## Minimum steps to reproduce

`0.126.0 ~`

- vrm-0.x that has `center` ( vroid model has `center` )
- move vrm-0.x from origin( move `center` from origin )

## Describe the bug

- Using Vroid Studio 1.29.2 from Steam I create a character vertion VRM0.0 and update it using UniVRM,  but all the models imported do the same 
- The hair and clothes goes to the left no matter where the character is looking once I start the game in Unity 
- 
![image](https://github.com/user-attachments/assets/45692238-13a5-4be7-a0bc-3914740ffd21)
with the game off they looks good 
![image](https://github.com/user-attachments/assets/b9873fbe-a044-4f23-a3ca-9ad3706dc3da)

And sprint bones looks like this 
![image](https://github.com/user-attachments/assets/5d0edc71-ce71-4812-bb97-f31fcc2ceadc)

Here is the VRM character if you would like to test, maybe is the character but I have tried it in 2 different projects and always does the same.
https://drive.google.com/file/d/1TlG2lNjFKh0vNnVsZu9cukKcWMTk0Tg2/view?usp=drive_link

One solution I found is in the file secondary inside the model every part of the model have hit radious as 0 and drag force as 1, the movement could be a little strange with some animations but it works till the new release :D  

![image](https://github.com/user-attachments/assets/c3c6bedd-2593-460b-9003-a21dc79ebdc7)

**Comment by TheR20** [comment] 2024-09-26 22:23
I add a solution to this problem, that is change the values manual, if someone is having the same problem with the vertion 0.126 will help :D 

Regards!

**Comment by kuni-0930** [comment] 2024-10-03 02:12
It's not fixed in v0.127.0 either.
What I have found is that SpringBone goes wrong if I load an avatar and then use SetParent on a parent object that is not the origin to make the avatar a child.
If the parent object was at the origin, it may work properly.

**Comment by ousttrue** [comment] 2024-10-15 04:12
SpringBone has been cleaned up, so please try it with `v0.128`.
If it doesn't work,
Please let us know which springbone (vrm0.x, vrm0.x-fast or vrm1.0).

**Comment by TheR20** [comment] 2024-10-19 05:45
Hello I test the version v0.127.1 with a vrm0.x, and its working the same way

**Comment by kuni-0930** [comment] 2024-10-19 13:12
> SpringBone has been cleaned up, so please try it with ~`v0.128`~ `v0.127.1` or later. If it doesn't work, Please let us know which springbone (vrm0.x, vrm0.x-fast or vrm1.0).

I tried it myself, but v0.127.1 did not fix the problem.

**Comment by ousttrue** [comment] 2024-10-21 14:10
Please tell me the steps to initialize SpringBone. Which of the following four?

- 0.x runtime load
- 0.x Scene placement start
- 1.0 runtime load
- 1.0 Start scene placement

I think runtime load has been resolved.
Scene placement starts I will add a solution when the model is not facing forward at the origin.

**Comment by kuni-0930** [comment] 2024-10-21 15:17
> Please tell me the steps to initialize SpringBone. Which of the following four?
> 
> * 0.x runtime load
> * 0.x Scene placement start
> * 1.0 runtime load
> * 1.0 Start scene placement
> 
> I think runtime load has been resolved. If scene placement, I will add a solution when the model is not facing forward at the origin.


[0.x runtime load]
It can also be reproduced in UniVRM_Samples-0.127.1_0214.
1. Place a GameObject on the Scene and play it.
GameObject should have rotation.y set to 180 (it does not have to be the origin).
2. Make the runtime loaded model a child of the GameObject with SetParent.
Then SpringBone will behave incorrectly.

```

    public class VRMRuntimeExporter : MonoBehaviour
    {
        [SerializeField]
        public GameObject obj;

        async void Load()
        {
            /*
            // omission
            */
            m_model = loaded.gameObject;
            m_model.transform.SetParent(obj.transform, false);
        }

    }
```

**Comment by ousttrue** [comment] 2024-10-22 06:08
I thought it was an initialization bug.
It doesn't reproduce on Alicia, but it occurs on Vroid, so I investigated.
It seems like a bug in `center`. I'll fix it.

**Closed** 2024-10-22 15:12 UTC
Labels: bug, SpringBone

**Comment by ousttrue** [comment] 2024-10-28 06:25
https://github.com/vrm-c/UniVRM/releases/tag/v0.127.2

fixed !.

**Comment by kuni-0930** [comment] 2024-10-30 07:06
> https://github.com/vrm-c/UniVRM/releases/tag/v0.127.2
> 
> fixed !.

I have checked v0.127.2 and it seems to be working properly.
thank you so much.
