### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by pupcakie** [vrm-c/UniVRM#2494] opened 2024-11-10 01:44 UTC
## Environments (please complete the following information):

- UniVRM version: `0.127.2`
- Unity version: `Unity 6`
- OS: `Windows 10`

## Error when exporting model - Object Reference not set to an instance of an object

NullReferenceException: Object reference not set to an instance of an object
VRM.VrmGeometryBackup..ctor (UnityEngine.GameObject root) (at Assets/VRM/Runtime/IO/VrmGeometryBackup.cs:76)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, UniGLTF.IMaterialExporter materialExporter, System.Collections.Generic.List`1[T] destroy) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:211)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, UniGLTF.IMaterialExporter materialExporter) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:29)
VRM.VRMExporterWizard.ExportPath (System.String path) (at Assets/VRM/Editor/Format/VRMExporterWizard.cs:261)
UniGLTF.ExportDialogBase.EndGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:162)
UniGLTF.ExportDialogBase.OnGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:82)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at <eebf6a509b354512a5d405c8a7dd6f88>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) (at <eebf6a509b354512a5d405c8a7dd6f88>:0)
UnityEditor.DockArea.OldOnGUI () (at <eebf6a509b354512a5d405c8a7dd6f88>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEventBubbleUp (UnityEngine.UIElements.EventBase evt) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.EventDispatchUtilities.HandleEventAcrossPropagationPathWithCompatibilityEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.EventBase compatibilityEvt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement target, System.Boolean isCapturingTarget) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.EventDispatchUtilities.DispatchToCapturingElementOrElementUnderPointer (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, System.Int32 pointerId, UnityEngine.Vector2 position) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.PointerEventBase`1[T].Dispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <7fd37b296550485d95ecaf5a50ed53b2>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <c2a7fdde9f43450eb67bbb9adb27f62f>:0)

![image](https://github.com/user-attachments/assets/24de794b-fffa-4fd1-b6b5-cb7e060aaccb)

- Reproduction procedure

- File that causes an error (those that can be pasted here)

Just to add - i barely have any real clue what im doing with an error like this so i have no clue what this is saying and it is driving me mad

**Comment by ousttrue** [comment] 2024-11-11 04:29
duplicate of VrmGeometryBackup #2479

**Closed by ousttrue** 2024-11-11 04:29 UTC
Labels: bug
